Update veracode-iac-secrets-scan.yml

diff --git a/.github/workflows/veracode-iac-secrets-scan.yml b/.github/workflows/veracode-iac-secrets-scan.yml
--- a/.github/workflows/veracode-iac-secrets-scan.yml
+++ b/.github/workflows/veracode-iac-secrets-scan.yml
@@ -94,6 +94,18 @@ jobs:
           echo "=== Contents After Cleanup ==="
           ls -lah "$GITHUB_WORKSPACE" || echo "Directory removed or empty."
 
+      - name: Remove helper/cli folder
+        run: |
+          echo "=== Before removal ==="
+          ls -R "$GITHUB_WORKSPACE/helper" || echo "No helper folder found."
+
+          echo
+          echo "=== Removing helper/cli folder... ==="
+          rm -rf "$GITHUB_WORKSPACE/helper/cli" || echo "CLI folder not found."
+
+          echo
+          echo "=== After removal ==="
+          ls -R "$GITHUB_WORKSPACE/helper" || echo "Helper folder empty or removed."
       - name: Explore workspace hierarchy
         run: |
           echo "=== Current workspace ==="
@@ -123,11 +135,12 @@ jobs:
 
           echo "=== One level up ==="
           ls -lah "$GITHUB_WORKSPACE/.." || echo "No parent directory found"
+          pwd
           echo
 
           echo "=== Two levels up ==="
           ls -lah "$GITHUB_WORKSPACE/../.." || echo "No grandparent directory found"
+          pwd
           echo
-
-          echo "=== Searching for any 'veracode-cli' folders recursively ==="
-          find "$GITHUB_WORKSPACE" -type d -name "veracode-cli" || echo "No veracode-cli folder found"
+          echo "=== Two levels up ==="
+          ls -lah "$GITHUB_WORKSPACE/../../.." || echo "No grandparent directory found"
