Update veracode-iac-secrets-scan.yml

diff --git a/.github/workflows/veracode-iac-secrets-scan.yml b/.github/workflows/veracode-iac-secrets-scan.yml
--- a/.github/workflows/veracode-iac-secrets-scan.yml
+++ b/.github/workflows/veracode-iac-secrets-scan.yml
@@ -80,11 +80,11 @@ jobs:
           echo "=== Full tree ==="
           find "$GITHUB_WORKSPACE"
 
-      - name: Cleanup workspace and Docker
-        run: |
-          echo "=== Running final cleanup... ==="
-          sudo rm -rf "$GITHUB_WORKSPACE"/*
-          echo "=== Cleanup complete ==="
+      # - name: Cleanup workspace and Docker
+      #   run: |
+      #     echo "=== Running final cleanup... ==="
+      #     sudo rm -rf "$GITHUB_WORKSPACE"/*
+      #     echo "=== Cleanup complete ==="
           
       - name: Print workspace info after cleanup
         run: |
@@ -94,3 +94,15 @@ jobs:
           echo "=== Contents After Cleanup ==="
           ls -lah "$GITHUB_WORKSPACE" || echo "Directory removed or empty."
 
+      - name: Remove helper/cli folder
+        run: |
+          echo "=== Before removal ==="
+          ls -R "$GITHUB_WORKSPACE/helper" || echo "No helper folder found."
+
+          echo
+          echo "=== Removing helper/cli folder... ==="
+          rm -rf "$GITHUB_WORKSPACE/helper/cli" || echo "CLI folder not found."
+
+          echo
+          echo "=== After removal ==="
+          ls -R "$GITHUB_WORKSPACE/helper" || echo "Helper folder empty or removed."
